### ISSUE TITLE
toBinaryString does not consider negative numbers

### ISSUE THREAD

**Issue by mightymercado** [rwpenney/spfpm#5]
![image](https://user-images.githubusercontent.com/11026445/39834807-b80e9970-5400-11e8-82b3-f22b00fc8124.png)
Please consider it.

**Comment by rwpenney** [comment]
Thank you for your comment.

I think you'll find that the `FXnum.toBinaryString()` method does already consider negative numbers, via the `_toTwosComplement()` method.

Perhaps you disagree with the design decision that twos-complement is the more useful way of representing binary numbers that happen to be negative? I agree this could be better documented (which I'll fix soon).

**Comment by rwpenney** [comment]
An option to switch between twos-complement or signed binary representations was added in commit 7fe947f0. Documentation of the `toBinaryString()` method was also improved.
