### ISSUE TITLE
Rounding seems erroneous

### ISSUE THREAD

**Issue by ajauhar-fw** [rwpenney/spfpm#6]
The fixed point scaling from this library seems wrong

For example, for a family object of FXFamily(4,8), the fixed point scaled value for 1.0525 is calculated to be 1.0. It should be 1.0625.
 This is probably because scaledval does not seem to rounded properly (always takes the floor.)

**Comment by ajauhar-fw** [comment]
Issue can be fixed on python 3 by replacing all int(x) by int(round(x)). Closing this issue.

**Comment by rwpenney** [comment]
Thanks for flagging this issue, and for your helpful suggestion of a fix.
I'll investigate, and hope to release an update shortly.
