### ISSUE TITLE
toBinaryString() fails with n_intbits less than 2

### ISSUE THREAD

**Issue by hartib** [rwpenney/spfpm#7]
toBinaryString() fails in that case because the conversion of 1 to a FXnum fails in __rmul__ line 425 (called from line 515). Would be nice to be able to use such numbers for hardware-related tasks.

**Comment by rwpenney** [comment]
Thanks for querying this, which is an interesting edge-case.
With FXnum implicitly being a *signed* quantity, if n_intbits=1 and there are f fractional bits, the range of allowed values is from -1 to slightly less than 1-2^{-f}, so +1 isn't representable as you've found.
I'll see if I can adjust .toBinaryString() so it handles this more gracefully.

**Comment by rwpenney** [comment]
Fixed in commit c55978377f188ff98b5392ae5685a4564cb6d7e5
